"use client";
import Link from "next/link";
import { useState } from "react";

const card: React.CSSProperties={background:"white",border:"1px solid var(--color-border)",borderRadius:10,padding:20}; const input: React.CSSProperties={width:"100%",padding:"10px 12px",border:"1px solid var(--color-border)",borderRadius:7,background:"white"};
export function EntityForm({kind,edit=false}:{kind:"Employee"|"Client"|"House / Service";edit?:boolean}){const [saved,setSaved]=useState(false);const fields=kind==="Employee"?["Full name","Email address","Phone number","Role","Assigned house / service","Employment status"]:kind==="Client"?["Full name","Preferred name","Date of birth","House / service","Support level","Status"]:["Service name","Street address","Suburb","City","Service status","Primary contact"];
return <div className="workflow-page"><PageHead title={`${edit?"Edit":"Add"} ${kind}`} subtitle="Changes in this demonstration are kept in the browser only."/><form onSubmit={e=>{e.preventDefault();setSaved(true)}}><section style={card}><h2>{kind==="Employee"?"Personal & employment details":kind==="Client"?"Personal & support details":"Service details"}</h2><div className="form-grid">{fields.map((f,i)=><label key={f}>{f}{i<2&&<span className="required"> *</span>}{f.includes("status")||f==="Role"||f.includes("house")?<select style={input} defaultValue=""><option value="" disabled>Select an option</option><option>Active</option><option>Riverside Lodge</option><option>Support Worker</option></select>:<input required={i<2} style={input} defaultValue={edit?sampleValue(f):""}/>}</label>)}</div></section><section style={card}><h2>Additional information</h2><label>Notes<textarea style={{...input,minHeight:100}} placeholder="Add relevant operational notes"/></label>{kind==="Employee"&&<p className="system-note">Account status and audit history are system-managed and cannot be edited here.</p>}</section><div className="form-actions"><Link className="button secondary" href={kind==="Employee"?"/employees":kind==="Client"?"/clients":"/houses"}>Cancel</Link><button className="button primary" type="submit">Save {kind}</button></div>{saved&&<div className="toast" role="status">✓ {kind} saved successfully</div>}</form></div>}
function sampleValue(f:string){return f.includes("name")?"Jamie Taufa":f.includes("Email")?"jamie.taufa@caremetrics.co.nz":f.includes("Phone")?"021 555 0142":""}
export function EmployeeDetail(){const [tab,setTab]=useState("Personal information");const tabs=["Personal information","Availability","Upcoming roster","Attendance","Leave"];
return <div className="workflow-page"><PageHead title="Jamie Taufa" subtitle="Support Worker · Riverside Lodge" actions={<><span className="status active">● Active</span><Link className="button secondary" href="/employees/jamie/edit">Edit employee</Link></>}/><div className="profile-banner" style={card}><span className="large-avatar">JT</span><div><h2>Jamie Taufa</h2><p>jamie.taufa@caremetrics.co.nz · 021 555 0142</p></div><dl><div><dt>Account</dt><dd>Enabled</dd></div><div><dt>Started</dt><dd>14 Mar 2022</dd></div></dl></div><div className="tabs" role="tablist">{tabs.map(t=><button role="tab" aria-selected={tab===t} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><div className="detail-grid"><section style={card}><h2>{tab}</h2>{tab==="Personal information"?<InfoRows/>:<MockSummary tab={tab}/>}</section><aside style={card}><h2>Employment</h2><p><small>ROLE</small><br/>Support Worker</p><p><small>ASSIGNED SERVICE</small><br/>Riverside Lodge</p><p><small>STATUS</small><br/>Permanent · 32 hours/week</p><button className="danger-link">Deactivate employee</button></aside></div></div>}
function InfoRows(){return <dl className="info-rows"><div><dt>Preferred name</dt><dd>Jamie</dd></div><div><dt>Phone</dt><dd>021 555 0142</dd></div><div><dt>Emergency contact</dt><dd>Available to authorised managers</dd></div><div><dt>Address</dt><dd>Auckland, New Zealand</dd></div></dl>}
function MockSummary({tab}:{tab:string}){return <div className="empty-inline"><strong>{tab} summary</strong><p>Mock records demonstrate how this section will display once connected to the CAREMetrics data service.</p></div>}
export function RecordDetail(){return <div className="workflow-page"><PageHead title="Care record CR-1048" subtitle="Historical record · Read only"/><div className="detail-grid"><section style={card}><div className="record-meta"><span className="status active">✓ Complete</span><span>Recorded 17 Aug 2026, 9:42 am</span></div><h2>Personal Care</h2><p className="system-note">Template: Personal Care · Version 3. Editing the current template will not change this record.</p><dl className="info-rows"><div><dt>Personal care completed</dt><dd>Yes</dd></div><div><dt>Support required</dt><dd>Prompting and minimal assistance</dd></div><div><dt>Wellbeing rating</dt><dd>4 / 5</dd></div><div><dt>Notes</dt><dd>Client was settled and engaged throughout morning support.</dd></div></dl></section><aside style={card}><h2>Record details</h2><p><small>CLIENT</small><br/>Mereana Rangi</p><p><small>RECORDED BY</small><br/>Jamie Taufa</p><p><small>CARE SECTION</small><br/>Personal Care</p></aside></div></div>}
export function CareEntry(){const [step,setStep]=useState(0);const labels=["Complete form","Review","Confirmation"];return <div className="workflow-page"><PageHead title="Personal Care" subtitle="Mereana Rangi · Template version 3"/><ol className="steps">{labels.map((l,i)=><li className={i<=step?"active":""} key={l}><span>{i+1}</span>{l}</li>)}</ol><section style={{...card,maxWidth:760}}>{step===0?<form onSubmit={e=>{e.preventDefault();setStep(1)}}><h2>Personal Care</h2><p>Complete all required fields before reviewing the record.</p><div className="field-stack"><label>Personal care completed <span className="required">*</span><select required style={input}><option value="">Select</option><option>Yes</option><option>No</option></select></label><label>Support required <span className="required">*</span><textarea required style={{...input,minHeight:90}}/></label><label>Wellbeing rating <span className="required">*</span><input required type="range" min="1" max="5" defaultValue="4"/></label><label>Additional notes<textarea style={{...input,minHeight:90}}/></label></div><button className="button primary">Review record</button></form>:step===1?<><h2>Review before submitting</h2><dl className="info-rows"><div><dt>Personal care completed</dt><dd>Yes</dd></div><div><dt>Support required</dt><dd>Prompting and minimal assistance</dd></div><div><dt>Wellbeing rating</dt><dd>4 / 5</dd></div></dl><div className="form-actions"><button className="button secondary" onClick={()=>setStep(0)}>Back</button><button className="button primary" onClick={()=>setStep(2)}>Submit care record</button></div></>:<div className="success-state"><span>✓</span><h2>Care record submitted</h2><p>The Personal Care record for Mereana Rangi has been saved.</p><Link className="button primary" href="/employee/clients">Return to My Clients</Link></div>}</section></div>}
function PageHead({title,subtitle,actions}:{title:string;subtitle:string;actions?:React.ReactNode}){return <header className="workflow-head"><div><h1>{title}</h1><p>{subtitle}</p></div>{actions&&<div className="head-actions">{actions}</div>}</header>}
